debian: Depend on exact version of gstreamer1.0-plugins-good
This makes the installation of kurento package to upgrade
gstreamer1.0-plugins-good, if it happened to be already installed in an
earlier (system default) version.

Otherwise, upon installation of gstreamer1.0-plugins-good-kurento, the
actual gstreamer1.0-plugins-good will not be upgraded.

Note that debian/control cannot be deleted: kurento-buildpackage expects
it to exist so build dependencies can be installed before attempting to
build the package itself.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -28,6 +28,7 @@ command -v dch >/dev/null || {
     exit 1
 }
 command -v dpkg-buildpackage >/dev/null || {
+    # Includes 'dpkg-parsechangelog'
     echo "ERROR: 'dpkg-buildpackage' is not installed; please install it (package 'dpkg-dev')"
     exit 1
 }
@@ -48,7 +49,7 @@ export DEBIAN_FRONTEND="noninteractive"
 
 # Uncomment system's source repositories.
 sed --regexp-extended --in-place \
-    's/# *(deb-src.*(main|restricted|universe|multiverse))/\1/' \
+    's/# *(deb-src.*focal.*(main|restricted|universe|multiverse))/\1/' \
     /etc/apt/sources.list
 
 apt-get update
@@ -60,7 +61,10 @@ apt-get update
 
 PACKAGE_NAME="gstreamer1.0-plugins-good"
 
-SOURCE_NAME="$(apt-cache madison "$PACKAGE_NAME" | grep Sources | head -n1 | awk '{print $1}')"
+SOURCE_NAME="$(apt-cache madison "$PACKAGE_NAME" | grep Sources | head -n1 | awk '{print $1}')" || {
+    echo "ERROR: Cannot find source repos for apt-get; make sure they are enabled in your system"
+    exit 1
+}
 
 apt-get build-dep --yes "$SOURCE_NAME"
 
@@ -88,7 +92,7 @@ quilt refresh
 # Add a new changelog entry. Ensure that the Debian package version's Epoch
 # is higher, to avoid it from getting replaced with system's updates.
 # See Debian New Maintainers' Guide for info about Epoch in version numbers.
-dch --local '-kurento' 'Apply patches for Kurento.'
+dch --local 'kurento' 'Apply patches for Kurento.'
 
 function increment_epoch {
     local VERSION
@@ -100,13 +104,15 @@ function increment_epoch {
     # shellcheck disable=SC2016
     sed -ri '1 s/(.*\()([0-9]+:)?(.*)/echo "\1$EPOCH:\3"/e' debian/changelog
 }
-
 increment_epoch
 
+# Store the definitive package version.
+PACKAGE_VERSION="$(dpkg-parsechangelog --show-field Version)"
 
 
-# Build package
-# =============
+
+# Build source package
+# ====================
 
 dpkg-buildpackage -us -uc -b
 
@@ -114,3 +120,11 @@ popd # $SOURCE_NAME
 
 # Move everything up; it is a convention to leave packages in the parent dir.
 mv ./*.*deb ../
+
+
+
+# Configure debian files
+# ======================
+
+sed "s/@PACKAGE_VERSION@/$PACKAGE_VERSION/g" debian/control.in \
+    > debian/control
